trigger: 
 branches:
    include:
      - main
pool:
 name: kaushal_self_hosted_agent_pool

stages:
  - stage: initialization
    displayName: perform init and plan
    jobs:
      - job: init_job
        displayName: my first job
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'Pay-As-You-Go(15d0a1ab-243a-42f8-8179-a3417894b311)'
            scriptType: 'ps'
            scriptLocation: 'inlineScript'
            inlineScript: 'az login'
            powerShellErrorActionPreference: 'silentlyContinue'
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Pay-As-You-Go(15d0a1ab-243a-42f8-8179-a3417894b311)'
            backendAzureRmOverrideSubscriptionID: '15d0a1ab-243a-42f8-8179-a3417894b311'
            backendAzureRmResourceGroupName: 'rgg'
            backendAzureRmStorageAccountName: 'kaushal12345'
            backendAzureRmContainerName: 'rgcontainer'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'Pay-As-You-Go(1)(15d0a1ab-243a-42f8-8179-a3417894b311)'
            environmentAzureRmOverrideSubscriptionID: '15d0a1ab-243a-42f8-8179-a3417894b311'
            environmentAzureRmUseIdTokenGeneration: true
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'Pay-As-You-Go(2)(15d0a1ab-243a-42f8-8179-a3417894b311)'
            environmentAzureRmOverrideSubscriptionID: '15d0a1ab-243a-42f8-8179-a3417894b311'
            environmentAzureRmUseIdTokenGeneration: true